# Site settings
name: Yongsheng Xiao
email: xiaoyongsheng@hotmail.com
author: Xiao
url: http://betterxys.github.io
resume_site: ''
github: https://github.com/betterxys/
baseurl: ""
description: It's always better if you have people to share it with!
meta_description: 肖永生;个人博客;
motto: 生若直木，不语斧凿.
banner: 假如一个人活在无法抗拒的痛苦当中，就会把这种痛苦看作幸福。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: betterxys
highlighter: rouge

# gems: [jekyll-paginate]
plugins: ['jekyll-paginate', 'jekyll-mermaid']
# mermaid: true
# Build settings
markdown: kramdown

# keamdown:
#     auto_ids: true
#     toc_levels: 1..3
#     input: GFM

mermaid:
  src: '/styles/js/mermaid.min.js'
