# Site settings
name: Xiao Yongsheng
email: xiaoyongsheng@hotmail.com
author: Xiao
url: http://betterxys.github.io
resume_site: ''
github: https://github.com/betterxys/
baseurl: ""
description: It's always better if you have people to share it with!
meta_description: 肖永生;个人博客;
motto: 等我找到合适的放在这.
banner: 不找了找不到了。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: betterxys
highlighter: rouge

# Build settings
markdown: kramdown

keamdown:
    auto_ids: true
    toc_levels: 1..3
    input: GFM